### ISSUE TITLE
Cannot see my ip address on the example heroku website

### ISSUE THREAD

**Issue by lin88362283** [joeymalvinni/webrtc-ip#2]
I opened the example link https://webrtc-ip.herokuapp.com/  but did not find my IP address on it. Is it still working?

**Comment by joeymalvinni** [comment]
Hi! Thanks for using webrtc-ip. It works fine on all of my devices. What browser are you using? Thanks!

**Comment by joeymalvinni** [comment]
I am closing this issue because I have not received a response. Let me know if you would like to reopen it.
