### ISSUE TITLE
Example website takes a long time to load

### ISSUE THREAD

**Issue by Octem** [joeymalvinni/webrtc-ip#3]
When I navigate to the [example website](https://webrtc-ip.herokuapp.com), it takes a long time to load the website.

Is this related to the actual package? Or, is this related to Node using the express framework?

Thanks.

**Comment by joeymalvinni** [comment]
Sorry for the late response.

This is probably to do with Heroku, and not my Node.js code. Heroku puts my apps to sleep after 30 minutes of inactivity, which causes them to load up again at a much slower rate. 

Thanks for using webrtc-ip.
